defaults: &defaults
  adapter: mysql2
  username: dp_gifts
  password: 
  host: localhost

production:
  <<: *defaults
  database: dp_gifts_dev

development:
  <<: *defaults
  database: dp_gifts_dev

test:
  <<: *defaults
  database: dp_gifts_test
